@local = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2YwZmQ4YTU1ZTQ3ZjkzODU5MmNjZjEiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjc2NzkzODEzfQ.yk_X9KXc4H8hNkU3mraqhZShqjCUZwgYDTCQpaUgIQk

###

GET {{local}}/projectmania/auth/get/63f0fd8a55e47f938592ccf1
Content-Type: application/json
x-auth-token: {{token}}

###

GET {{local}}/projectmania/projects/63f62c3c28538648fac0e2d5/63f63f3161480aa8d9f0fd0f
x-auth-token: {{token}}
Content-Type: application/json

###

PUT {{local}}/projectmania/projects/63f62c3c28538648fac0e2d5
Content-Type: application/json
x-auth-token: {{token}}

{
    "created_at": "",
    "due_date": "",
    "edit_active": false,
    "members": [],
    "options_menu_open": false,
    "stages": [],
    "subtitle": "",
    "title": "",
    "_id": ""
}

###

POST {{local}}/projectmania/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}

###

POST {{local}}/projectmania/auth/register
Content-Type: application/json

{
    "first_name": "tomross",
    "last_name": "rosssssner",
    "email": "tomross@gmail.com",
    "password": "tom123",
    "is_admin": true
}

###

GET {{local}}/projectmania/projects/63f0fd8a55e47f938592ccf1/all
Content-Type: application/json
x-auth-token: {{token}}

###

DELETE {{local}}/projectmania/projects/63f7970f3f833446bf4e25c0/63f7970f3f833446bf4e25c1/63f79af2a47407e7d7b67aa9
Content-Type: application/json
x-auth-token: {{token}}
