@local = http://localhost:5000

###

GET {{local}}/projects/all
Content-Type: application/json

###

GET {{local}}/projectmania/projects/63ed61b443aa8b665ba8f7cc/63ee65c7384c7bded2c77595
Content-Type: application/json

###

PUT {{local}}/projects/update
Content-Type: application/json

{
    "created_at": "",
    "due_date": "",
    "edit_active": false,
    "members": [],
    "options_menu_open": false,
    "stages": [],
    "subtitle": "",
    "title": "",
    "_id": ""
}

###

POST {{local}}/projectmania/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}

###

POST {{local}}/projectmania/auth/register
Content-Type: application/json

{
    "first_name": "tomross",
    "last_name": "rosssssner",
    "email": "tomross@gmail.com",
    "password": "tom123",
    "is_admin": true
}