@local = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2YwZmQ4YTU1ZTQ3ZjkzODU5MmNjZjEiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjc2NzkzODEzfQ.yk_X9KXc4H8hNkU3mraqhZShqjCUZwgYDTCQpaUgIQk

###

GET {{local}}/projectmania/auth/get/63f0fd8a55e47f938592ccf1
Content-Type: application/json
x-auth-token: {{token}}

###

GET {{local}}/projectmania/projects/63ed61b443aa8b665ba8f7cc/63ee65c7384c7bded2c77595
x-auth-token: {{token}}
Content-Type: application/json

###

PUT {{local}}/projects/update
Content-Type: application/json

{
    "created_at": "",
    "due_date": "",
    "edit_active": false,
    "members": [],
    "options_menu_open": false,
    "stages": [],
    "subtitle": "",
    "title": "",
    "_id": ""
}

###

POST {{local}}/projectmania/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}

###

POST {{local}}/projectmania/auth/register
Content-Type: application/json

{
    "first_name": "tomross",
    "last_name": "rosssssner",
    "email": "tomross@gmail.com",
    "password": "tom123",
    "is_admin": true
}

###

GET {{local}}/projectmania/projects/63f0fd8a55e47f938592ccf1/all
Content-Type: application/json
x-auth-token: {{token}}